### PR TITLE
fix(transformers): chunkify only chunking first chunks

### LINKED ISSUE #3: chunkify only iterates first chunk
## How to reproduce
```ts
import { assertEquals } from "https://deno.land/std@0.84.0/testing/asserts.ts"
import { chunkify } from "https://deno.land/x/iter@v3.0.0/mod.ts"

const numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
const expected = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]

assertEquals([...chunkify(numbers, 2)], expected)
```

## Result
<details><summary>error message</summary>

```
Uncaught AssertionError: Values are not equal:


    [Diff] Actual / Expected


    [
      [
        0,
        1,
      ],
+     [
+       2,
+       3,
+     ],
+     [
+       4,
+       5,
+     ],
+     [
+       6,
+       7,
+     ],
+     [
+       8,
+       9,
+     ],
    ]

    at assertEquals (https://deno.land/std@0.84.0/testing/asserts.ts:214:9)
    at <anonymous>:38:1
```

</details> 

## Reason
image

the `return` statement is inside the for loop, only executing it once.

### PR DESCRIPTION
**Pull request by scarf005**
- fixes #3

### CODE REVIEW

**Comment by jajaperson** [comment]
thanks for spotting that, those tests I wrote were actually awful. you've also brought to my attention that the internal `stripIterable` utility isn't doing what it's supposed to do. not too big of a deal since that function is only used in tests, but it should probably just be removed (unless it can be made to work). I can't fix that right now, but I will get to it soon — otherwise you're welcome to do it.

**Comment by scarf005** [comment]
alright, i'll also remove the `stripIterable` function and their related usages as well.
...oh wait, if you meant fixing `stripIterable`, could you explain how should the `stripIterable` function behave, and which situation makes it doesn't?

**Comment by scarf005** [comment]
would there be anything else i'd need to do to get it merged?

**Comment by scarf005** [comment]
@jajaperson

**Comment by jajaperson** [comment]
apologies, i have had pretty bad covid the last week and haven't gotten to this. since the code works and the problem with`stripIterable` does not affect it, i see no reason not to merge this as is.

**Comment by scarf005** [comment]
thank you! i've also gotten covid a few months ago, hope you get well soon.

**Pull request merged**
